services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/apache.dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ../tallerlaravel:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mariadb:11
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravelCourse
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8090:80"
    depends_on:
      - db
    networks:
      - laravel
  
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ../tallerlaravel:/app
    working_dir: /app
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge